name: tabular
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  permission_handler: ^10.2.0
  url_launcher: ^6.1.9
  flutter_downloader: ^1.10.2
  intl: ^0.18.0
  crypto: ^3.0.2
  path_provider: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

